# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sync some data with third parties

Resources:
    SyncStatsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: sync-data.default
            Runtime: nodejs10.x
            # Because of BG games
            Timeout: 30
            CodeUri: ./dist/sync-data
            MemorySize: 384 # Increase memory to be able to handle big games like BGS
            ReservedConcurrentExecutions: 5
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: trigger-sync-data
            Events:
                ReviewPublishedSnsTopic:
                    Type: SNS
                    Properties:
                        Topic: arn:aws:sns:us-west-2:478062583808:review-published
    ReprocessStatsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: sync-data-reprocess.default
            # Runtime: nodejs8.10 # Used for dev
            Runtime: nodejs10.x
            Timeout: 10
            CodeUri: ./dist/sync-data-reprocess
            MemorySize: 384 # Increase memory to be able to handle big games like BGS
            ReservedConcurrentExecutions: 40
            # https://stackoverflow.com/questions/39144688/aws-lambda-invoke-not-calling-another-lambda-function-node-js
            # VpcConfig:
            #     SecurityGroupIds:
            #         - sg-0ed63616362bf1a30
            #     SubnetIds:
            #         - subnet-0b36da5c19637a351
            #         - subnet-0b730ca9af74a95dd
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: trigger-sync-data-reprocess
            Events:
                SQSReprocess:
                    Type: SQS
                    Properties:
                        Queue: arn:aws:sqs:us-west-2:478062583808:review-reprocess
                        BatchSize: 1
