# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sync some data with third parties

Resources:
    ProcessSyncStatsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: process-sync-stats.default
            Runtime: nodejs10.x
            CodeUri: ./dist/process-sync-stats
            Timeout: 30 # Because of BG games
            MemorySize: 384 # Increase memory to be able to handle big games like BGS
            ReservedConcurrentExecutions: 5
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - SecretsManagerReadWrite
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: process-sync-stats
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        Queue: arn:aws:sqs:us-west-2:478062583808:ranked-review-published-queue
    ReprocessStatsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: sync-data-reprocess.default
            # Runtime: nodejs8.10 # Used for dev
            Runtime: nodejs10.x
            Timeout: 10
            CodeUri: ./dist/sync-data-reprocess
            MemorySize: 384 # Increase memory to be able to handle big games like BGS
            ReservedConcurrentExecutions: 40
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: trigger-sync-data-reprocess
            Events:
                SQSReprocess:
                    Type: SQS
                    Properties:
                        Queue: arn:aws:sqs:us-west-2:478062583808:review-reprocess
                        BatchSize: 1
