# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sync some data with third parties

Resources:
    SyncStatsStatsQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: sync-stats-queue
            VisibilityTimeout: 601
    SyncStatsSqsQueuePolicy:
        Type: AWS::SQS::QueuePolicy
        Properties:
            PolicyDocument:
                Version: '2012-10-17'
                Id: SyncStatsStatsQueuePolicy
                Statement:
                    - Sid: Allow-SNS-SendMessage
                      Effect: Allow
                      Principal:
                          AWS: '*'
                      Action:
                          - sqs:SendMessage
                      Resource: !GetAtt SyncStatsStatsQueue.Arn
                      Condition:
                          ArnEquals:
                              aws:SourceArn: arn:aws:sns:us-west-2:478062583808:review-published
            Queues:
                - !Ref SyncStatsStatsQueue
    SyncStatsSnsSubscription:
        Type: AWS::SNS::Subscription
        Properties:
            Protocol: SQS
            Endpoint: !GetAtt SyncStatsStatsQueue.Arn
            TopicArn: arn:aws:sns:us-west-2:478062583808:review-published

    ProcessSyncStatsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: process-sync-stats.default
            Runtime: nodejs16.x
            CodeUri: ./dist/process-sync-stats
            Timeout: 60 # Because of BG games
            MemorySize: 384 # Increase memory to be able to handle big games like BGS
            ReservedConcurrentExecutions: 10
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - SecretsManagerReadWrite
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: process-sync-stats
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt SyncStatsStatsQueue.Arn
    TriggerReprocessStatsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: trigger-sync-reprocess.default
            Runtime: nodejs16.x
            Timeout: 900
            CodeUri: ./dist/trigger-sync-reprocess
            MemorySize: 2048
            ReservedConcurrentExecutions: 5
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - AmazonSNSFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: trigger-sync-reprocess
    ReprocessStatsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: sync-data-reprocess.default
            Runtime: nodejs16.x
            Timeout: 10
            CodeUri: ./dist/sync-data-reprocess
            MemorySize: 384 # Increase memory to be able to handle big games like BGS
            ReservedConcurrentExecutions: 40
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: sync-data-reprocess
            Events:
                SQSReprocess:
                    Type: SQS
                    Properties:
                        Queue: arn:aws:sqs:us-west-2:478062583808:review-reprocess
                        BatchSize: 1
